In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("DateFruit_Dataset.csv")

In [3]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [4]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [5]:
df.shape

(898, 35)

In [6]:
# encode

X = df.drop("Class", axis=1)
y = df["Class"]

In [7]:
X

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.9080,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.1440,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.3940,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.2100,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.3540,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,255403,1925.3650,691.8453,477.1796,0.7241,570.2536,0.9785,261028,0.7269,1.4499,...,-0.1398,2.2423,2.3704,2.7202,-25296416768,-19168882688,-18473392128,49.0869,43.0422,42.4153
894,365924,2664.8230,855.4633,551.5447,0.7644,682.5752,0.9466,386566,0.6695,1.5510,...,0.5611,3.4109,3.5805,3.9910,-31605219328,-21945366528,-19277905920,46.8086,39.1046,36.5502
895,254330,1926.7360,747.4943,435.6219,0.8126,569.0545,0.9925,256255,0.7240,1.7159,...,0.2665,2.2759,2.5090,2.6951,-22242772992,-19594921984,-17592152064,44.1325,40.7986,40.9769
896,238955,1906.2679,716.6485,441.8297,0.7873,551.5859,0.9604,248795,0.6954,1.6220,...,0.5325,2.6769,2.6874,2.7991,-26048595968,-21299822592,-19809978368,51.2267,45.7162,45.6260
897,343792,2289.2720,823.8438,534.7757,0.7607,661.6113,0.9781,351472,0.6941,1.5405,...,0.4318,2.5138,3.0369,3.0865,-31983476736,-20482514944,-21219354624,47.3454,38.6966,39.6738

In [8]:
y

0      BERHI
1      BERHI
2      BERHI
3      BERHI
4      BERHI
       ...
893    SOGAY
894    SOGAY
895    SOGAY
896    SOGAY
897    SOGAY
Name: Class, Length: 898, dtype: object

In [9]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [10]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [13]:
X_train
X_test
y_train
y_test

array([2, 5, 2, 6, 0, 2, 3, 2, 2, 1, 1, 2, 2, 2, 4, 4, 6, 5, 6, 1, 5, 4,
       2, 4, 5, 2, 0, 6, 0, 5, 6, 1, 2, 4, 2, 5, 0, 2, 2, 5, 1, 4, 5, 5,
       2, 1, 1, 2, 2, 5, 4, 3, 2, 6, 2, 4, 1, 2, 2, 0, 3, 6, 2, 2, 2, 6,
       1, 2, 4, 4, 2, 2, 4, 6, 3, 4, 2, 4, 5, 4, 2, 1, 4, 4, 2, 4, 2, 5,
       3, 2, 2, 5, 5, 3, 1, 2, 2, 2, 2, 4, 4, 3, 2, 5, 5, 4, 3, 4, 4, 2,
       5, 2, 4, 4, 4, 6, 1, 5, 5, 4, 4, 2, 5, 1, 5, 5, 6, 1, 4, 4, 2, 1,
       3, 4, 4, 2, 4, 2, 5, 0, 5, 5, 5, 6, 6, 5, 2, 0, 0, 5, 6, 4, 6, 1,
       1, 5, 6, 1, 2, 3, 5, 2, 6, 5, 0, 0, 2, 4, 2, 4, 1, 6, 5, 6, 6, 5,
       0, 1, 0, 2])

In [14]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### ANN

In [15]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [16]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [17]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [18]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

In [19]:
# build our model

class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__()

        self.model = nn.Sequential(
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),

            nn.Linear(64,64),
            nn.ReLU(),

            nn.Linear(64,7)
        )

    def forward(self, x):
        return self.model(x)

In [20]:
model = ANN()

# loss and optimizer

criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [21]:
# training tha nn

epochs = 100

for epoch in range(epochs):
    model.train()

    running_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()
        
        outputs = model(xb)
        loss = criteria(outputs, yb)
        loss.backward()
        optimizer.step() # params update

        running_loss +=loss

    train_loss = running_loss/ len(train_loader)

    print(f"epoch = {epoch+1}/{epochs}, loss = {train_loss}")

epoch = 1/100, loss = 1.6606179475784302
epoch = 2/100, loss = 1.0749441385269165
epoch = 3/100, loss = 0.7002472877502441
epoch = 4/100, loss = 0.5300026535987854
epoch = 5/100, loss = 0.4545365571975708
epoch = 6/100, loss = 0.3933088183403015
epoch = 7/100, loss = 0.36065492033958435
epoch = 8/100, loss = 0.3341905474662781
epoch = 9/100, loss = 0.3100740909576416
epoch = 10/100, loss = 0.2803593575954437
epoch = 11/100, loss = 0.2628616690635681
epoch = 12/100, loss = 0.24087916314601898
epoch = 13/100, loss = 0.22591814398765564
epoch = 14/100, loss = 0.21687516570091248
epoch = 15/100, loss = 0.20587517321109772
epoch = 16/100, loss = 0.2013697773218155
epoch = 17/100, loss = 0.1858808696269989
epoch = 18/100, loss = 0.18275678157806396
epoch = 19/100, loss = 0.17467288672924042
epoch = 20/100, loss = 0.17050887644290924
epoch = 21/100, loss = 0.16141971945762634
epoch = 22/100, loss = 0.15896007418632507
epoch = 23/100, loss = 0.1556321680545807
epoch = 24/100, loss = 0.1564553827047348
epoch = 25/100, loss = 0.1556033492088318
epoch = 26/100, loss = 0.14294680953025818
epoch = 27/100, loss = 0.13793368637561798
epoch = 28/100, loss = 0.13618575036525726
epoch = 29/100, loss = 0.1354253590106964
epoch = 30/100, loss = 0.12540821731090546
epoch = 31/100, loss = 0.12460729479789734
epoch = 32/100, loss = 0.13170945644378662
epoch = 33/100, loss = 0.11777618527412415
epoch = 34/100, loss = 0.11995117366313934
epoch = 35/100, loss = 0.1112942174077034
epoch = 36/100, loss = 0.10653006285429001
epoch = 37/100, loss = 0.11111786216497421
epoch = 38/100, loss = 0.11021985113620758
epoch = 39/100, loss = 0.11940601468086243
epoch = 40/100, loss = 0.10159886628389359
epoch = 41/100, loss = 0.09896113723516464
epoch = 42/100, loss = 0.10462132841348648
epoch = 43/100, loss = 0.09242699295282364
epoch = 44/100, loss = 0.09249977767467499
epoch = 45/100, loss = 0.0907064750790596
epoch = 46/100, loss = 0.08928108960390091
epoch = 47/100, loss = 0.08372275531291962
epoch = 48/100, loss = 0.0806211456656456
epoch = 49/100, loss = 0.08422321081161499
epoch = 50/100, loss = 0.0844043418765068
epoch = 51/100, loss = 0.08433891832828522
epoch = 52/100, loss = 0.08025601506233215
epoch = 53/100, loss = 0.07298073917627335
epoch = 54/100, loss = 0.07213177531957626
epoch = 55/100, loss = 0.07655012607574463
epoch = 56/100, loss = 0.07288619875907898
epoch = 57/100, loss = 0.07521440833806992
epoch = 58/100, loss = 0.0700812116265297
epoch = 59/100, loss = 0.06960995495319366
epoch = 60/100, loss = 0.06519094109535217
epoch = 61/100, loss = 0.07206922024488449
epoch = 62/100, loss = 0.06895112246274948
epoch = 63/100, loss = 0.06764781475067139
epoch = 64/100, loss = 0.07801176607608795
epoch = 65/100, loss = 0.06765075027942657
epoch = 66/100, loss = 0.06679410487413406
epoch = 67/100, loss = 0.0630316510796547
epoch = 68/100, loss = 0.05808107927441597
epoch = 69/100, loss = 0.057055842131376266
epoch = 70/100, loss = 0.05665994808077812
epoch = 71/100, loss = 0.0580749548971653
epoch = 72/100, loss = 0.05634922906756401
epoch = 73/100, loss = 0.05910225585103035
epoch = 74/100, loss = 0.05449323728680611
epoch = 75/100, loss = 0.05245169997215271
epoch = 76/100, loss = 0.05265100672841072
epoch = 77/100, loss = 0.04856428503990173
epoch = 78/100, loss = 0.050560735166072845
epoch = 79/100, loss = 0.0548802874982357
epoch = 80/100, loss = 0.046732913702726364
epoch = 81/100, loss = 0.050672490149736404
epoch = 82/100, loss = 0.048337507992982864
epoch = 83/100, loss = 0.048880431801080704
epoch = 84/100, loss = 0.045923974364995956
epoch = 85/100, loss = 0.04691033810377121
epoch = 86/100, loss = 0.045344043523073196
epoch = 87/100, loss = 0.047540389001369476
epoch = 88/100, loss = 0.043551694601774216
epoch = 89/100, loss = 0.04122692719101906
epoch = 90/100, loss = 0.039667703211307526
epoch = 91/100, loss = 0.03843376785516739
epoch = 92/100, loss = 0.03808657079935074
epoch = 93/100, loss = 0.0408543236553669
epoch = 94/100, loss = 0.039379533380270004
epoch = 95/100, loss = 0.03558516129851341
epoch = 96/100, loss = 0.03460695594549179
epoch = 97/100, loss = 0.03464794531464577
epoch = 98/100, loss = 0.03764317184686661
epoch = 99/100, loss = 0.034040939062833786
epoch = 100/100, loss = 0.03405729681253433

In [24]:
# Evaluation
model.eval()

total = 0
correct = 0

with torch.no_grad():
    for xb, yb in test_loader:
        outputs = model(xb)

        _, predicted = torch.max(outputs, 1)

        correct += (predicted == yb).sum().item()
        total += yb.size(0) # actual samples in each batch


print("total values :",total)
print("Correct values: ",correct)

print("Accuracy score: ", correct/total * 100)

total values : 180
Correct values:  168
Accuracy score:  93.33333333333333